services:
  backend:
    build:
      context: ./components/backend
      dockerfile: Dockerfile
    networks:
      - debates_network
    environment:
      SOLR_URL: http://solr:8983/solr/debates/
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-instance:27017/
      MONGO_DB: debates
      S3_SERVER: http://minio-instance:9000
      S3_FRONTEND_BASE_URL: http://localhost:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      REDIS_URL: redis://redis:6379
    ports:
      - 8082:8000
    depends_on:
      mongodb-instance:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./components/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      PUBLIC_BACKEND_SERVER: http://backend:8000
    networks:
      - debates_network
    command: ["node", "build"]
