services:
  frontend:
    build:
      context: ./components/frontend
    container_name: frontend
    labels:
      - "dev.dozzle.name=Frontend"
      - "dev.dozzle.group=App"
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      PUBLIC_BACKEND_SERVER: ${PUBLIC_BACKEND_SERVER}
      ORIGIN: http://localhost:3000
    networks:
      - debates_network
    command: ["node", "build"]
    profiles:
      - prod
