services:
  frontend:
    build:
      context: ./components/frontend
    container_name: frontend
    labels:
      - "dev.dozzle.name=Frontend"
      - "dev.dozzle.group=App"
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      ORIGIN: http://localhost:3000
      TYPE_TRANSLATION: ${TYPE_TRANSLATION}
      TYPE_ORIGINAL: ${TYPE_ORIGINAL}
      PUBLIC_SEARCH_PAGE_SIZE: ${SEARCH_PAGE_SIZE}
    networks:
      - debates_network
    command: ["node", "build"]
    profiles:
      - prod
