services:
  workers:
    build: ./components/workers
    # CRITICAL: This command starts the listener
    command: rq worker --url redis://redis:6379
    container_name: workers
    labels:
      - "dev.dozzle.name=Workers"
      - "dev.dozzle.group=Ingestion"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - S3_SERVER=http://minio-instance:9000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-instance:27017/
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_MEDIA_COLLECTION=${MONGO_MEDIA_COLLECTION}
      - REDIS_URL=redis://redis:6379
      - HF_TOKEN=${HF_TOKEN}
      - HF_SPACE_URL=${HF_SPACE_URL}
      - HF_MODEL=${HF_MODEL}
      - HF_SRT_ORIGINAL="subtitles_original.srt"
      - HF_SRT_TRANSLATION="subtitles_original.srt"
      - HF_SUBTITLES_ORIGINAL_JSON=="subtitles_original.srt"
      - HF_SUBTITLES_TRANSLATION_JSON=="subtitles_translation.srt"
      - HF_SEGMENTS_ORIGINAL_PDF=="segments_original.pdf"
      - HF_SEGMENTS_TRANSLATION_PDF=="segments_translation.pdf"
      - HF_SEGMENTS_ORIGINAL_JSON=="segments_original.json"
      - HF_TRANSLATION_JSON=="segments_translation.json"
      - HF_SEGMENTS_ORIGINAL_MD=="segments_original.md"
      - HF_SEGMENTS_TRANSLATION_MD=="segments_translation.md"
      # Make sure Python can find your modules
      - PYTHONPATH=/app/src
    networks:
      - debates_network
