services:
  garage:
    build:
      context: components/garage
    container_name: garage
    restart: unless-stopped
    labels:
      - "dev.dozzle.name=Garage"
      - "dev.dozzle.group=Services"
    ports:
      - "3900:3900"
    volumes:
      - ${GARAGE_PATH}:/var/lib/garage
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    networks:
      - debates_network
