from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional, Dict
from enum import Enum


class DeleteMediaRequest(BaseModel):
    media_id: str = Field(..., description="The unique media ID generated by the backend")
