from pydantic import BaseModel, Field
from typing import Dict


class S3PostRequest(BaseModel):
    filename: str = Field(..., description="Original filename with extension (e.g., my_video.mp4)")


class S3PostResponse(BaseModel):
    postUrl: str = Field(..., description="The S3 endpoint URL to POST the file to")
    fields: Dict[str, str] = Field(..., description="Key-value fields required in the multipart form data")
    mediaId: str = Field(..., description="The unique media ID generated by the backend")
    s3Key: str = Field(..., description="The final S3 key where the file will be stored")


class ProcessRequest(BaseModel):
    s3_key: str = Field(..., description="The final S3 key where the file will be stored")
    media_id: str = Field(..., description="The unique job ID generated by the backend")
    title: str = Field(None, description="filename of the media")
