/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ingest/get-presigned-post": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get Presigned Post
     * @description [POST] Returns a presigned URL and creates the initial Mongodb record.
     *     Status -> 'preparing'
     */
    post: operations["get_presigned_post_ingest_get_presigned_post_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ingest/process": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Processing
     * @description [POST] Starts processing: starts redis queue with first task: converting
     *     the video to audio. Updates status on Mongo DB.
     *     Status -> 'preparing'
     */
    post: operations["start_processing_ingest_process_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/db/get-signed-urls": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get Media Urls
     * @description Get signed media urls for a debate.
     */
    post: operations["get_media_urls_db_get_signed_urls_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/db/get-metadata": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Mongo Metadata */
    get: operations["mongo_metadata_db_get_metadata_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/search-solr": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Search Solr */
    post: operations["search_solr_search_search_solr_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Media
     * @description Returns a list of all uploaded media for the dashboard.
     */
    get: operations["list_media_admin_list_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/status/{media_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check Processing Status
     * @description Combines MongoDB Status (Persistent) with Redis Status (Real-time).
     *     Frontend should poll this every 3-5 seconds.
     */
    get: operations["check_processing_status_admin_status__media_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/delete": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete Media
     * @description Nuclear Option: Deletes EVERYTHING.
     *     Uses 'Best Effort' strategy: if one service fails, it logs the error
     *     but continues trying to delete the others.
     */
    post: operations["delete_media_admin_delete_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/reindex/{media_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Trigger Reindex
     * @description Triggers the Solr Indexing process manually.
     *     Useful if you changed the Solr schema or parser logic.
     */
    post: operations["trigger_reindex_admin_reindex__media_id__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** DebateDocument */
    DebateDocument: {
      /** S3 Prefix */
      s3_prefix: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** S3 Keys */
      s3_keys: components["schemas"]["S3Key"][]
      media: components["schemas"]["Media"]
      /**
       * Schedule
       * Format: date-time
       */
      schedule: string
      /** Public */
      public: boolean
      /** Type */
      type: string
      /** Session */
      session: string
    }
    /** DeleteMediaRequest */
    DeleteMediaRequest: {
      /** Mediaid */
      mediaId: string
    }
    /** DeleteMediaResponse */
    DeleteMediaResponse: {
      /** Status */
      status: string
      /** Mediaid */
      mediaId: string
      /** Warnings */
      warnings?: string[] | null
      /** Errors */
      errors?: string[] | null
    }
    /** FacetField */
    FacetField: {
      /** Field Name */
      field_name: string
      /** Values */
      values: components["schemas"]["FacetValue"][]
    }
    /** FacetFilter */
    FacetFilter: {
      /**
       * Facetfield
       * @description Solr facet field name
       * @example statement_type
       */
      facetField: string
      /**
       * Facetvalue
       * @description Solr facet field value
       * @example translation
       */
      facetValue: string
    }
    /** FacetValue */
    FacetValue: {
      /** Label */
      label: string
      /** Count */
      count: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HighlightedDoc */
    HighlightedDoc: {
      /** Statement */
      statement?: string[] | null
    }
    /** Media */
    Media: {
      /** Key */
      key: string
      /** Type */
      type: string
      /** Format */
      format: string
    }
    /** MediaListItem */
    MediaListItem: {
      /** Media Id */
      media_id: string
      /** Filename */
      filename: string
      /** Status */
      status: string
      /** Created At */
      created_at?: string | null
      /** Title */
      title?: string | null
    }
    /** MediaListResponse */
    MediaListResponse: {
      /** Items */
      items: components["schemas"]["MediaListItem"][]
      /** Total */
      total: number
    }
    /** MetadataResponse */
    MetadataResponse: {
      [x: string]: any
      debate: components["schemas"]["DebateDocument"]
      speakers?: components["schemas"]["SpeakersDocument"] | null
      segments?: components["schemas"]["SegmentsDocument"] | null
      subtitles?: components["schemas"]["SubtitlesDocument"] | null
      subtitles_en?: components["schemas"]["SubtitlesDocument"] | null
    }
    /** ProcessRequest */
    ProcessRequest: {
      /**
       * S3 Key
       * @description The final S3 key where the file will be stored
       */
      s3_key: string
      /**
       * Media Id
       * @description The unique job ID generated by the backend
       */
      media_id: string
      /**
       * Title
       * @description filename of the media
       */
      title?: string
    }
    /** ProcessingStatusResponse */
    ProcessingStatusResponse: {
      /** Media Id */
      media_id: string
      /** Status */
      status: string
      /** Job Id */
      job_id: string | null
      /** Job State */
      job_state: string | null
      /** Progress */
      progress: string | null
      /** Error */
      error: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** S3Key */
    S3Key: {
      /** Name */
      name: string
      /** Type */
      type: string
      /** Description */
      description: string
    }
    /** S3MediaUrlRequest */
    S3MediaUrlRequest: {
      /**
       * Media Id
       * @description media_id
       * @example df2afc83-7e69-4868-ba4c-b7c4afed6218
       */
      media_id: string
    }
    /** S3MediaUrlResponse */
    S3MediaUrlResponse: {
      /**
       * Signedurls
       * @description List of presigned URLs
       */
      signedUrls: components["schemas"]["S3MediaUrls"][]
      /**
       * Signedmediaurl
       * @description Presigned URL for the main media file
       */
      signedMediaUrl: string
    }
    /** S3MediaUrls */
    S3MediaUrls: {
      /**
       * Url
       * @description Url
       */
      url: string
      /**
       * Label
       * @description Label for Url
       */
      label: string
    }
    /** S3PostRequest */
    S3PostRequest: {
      /**
       * Filename
       * @description Original filename with extension (e.g., my_video.mp4)
       */
      filename: string
    }
    /** S3PostResponse */
    S3PostResponse: {
      /**
       * Posturl
       * @description The S3 endpoint URL to POST the file to
       */
      postUrl: string
      /**
       * Fields
       * @description Key-value fields required in the multipart form data
       */
      fields: {
        [key: string]: string
      }
      /**
       * Mediaid
       * @description The unique media ID generated by the backend
       */
      mediaId: string
      /**
       * S3Key
       * @description The final S3 key where the file will be stored
       */
      s3Key: string
    }
    /** SearchDocument */
    SearchDocument: {
      /** Id */
      id: string
      /** Media Id */
      media_id: string
      /** Segment Nr */
      segment_nr: number
      /** Speaker Id */
      speaker_id: string
      /** Statement */
      statement: string[]
      statement_type: components["schemas"]["StatementType"]
      /** Start */
      start: number
      /** End */
      end: number
      /** Debate Schedule */
      debate_schedule?: string | null
      /** Debate Type */
      debate_type?: string | null
      /** Debate Session */
      debate_session?: string | null
      /** Debate Name */
      debate_name?: string | null
      /** Statement Language */
      statement_language?: string | null
    }
    /** SearchQuery */
    SearchQuery: {
      /**
       * Queryterm
       * @description Solr query term can be empty
       * @example honor
       */
      queryTerm: string
      /**
       * Sortby
       * @description Solr sort option
       * @example start asc
       */
      sortBy: string
      /**
       * Facetfields
       * @description Solr facet field to return
       * @example [
       *       "debate_schedule",
       *       "statement_type"
       *     ]
       */
      facetFields: string[]
      /**
       * Facetfilters
       * @description Solr facet filters with set values
       */
      facetFilters: components["schemas"]["FacetFilter"][]
    }
    /** SearchResponse */
    SearchResponse: {
      /** Items */
      items: components["schemas"]["SearchDocument"][]
      /** Total */
      total: number
      /**
       * Facets
       * @default []
       */
      facets: components["schemas"]["FacetField"][]
      /**
       * Highlighting
       * @default {}
       */
      highlighting: {
        [key: string]: components["schemas"]["HighlightedDoc"]
      }
    }
    /** Segment */
    Segment: {
      /** Segment Nr */
      segment_nr: number
      /** Speaker Id */
      speaker_id: string
      /** Start */
      start: number
      /** End */
      end: number
    }
    /** SegmentsDocument */
    SegmentsDocument: {
      /** Segments */
      segments: components["schemas"]["Segment"][]
    }
    /** Speaker */
    Speaker: {
      /** Speaker Id */
      speaker_id: string
      /** Name */
      name: string
      /** Role Tag */
      role_tag: string
    }
    /** SpeakersDocument */
    SpeakersDocument: {
      /** Speakers */
      speakers: components["schemas"]["Speaker"][]
    }
    /**
     * StatementType
     * @enum {string}
     */
    StatementType: "original" | "translation"
    /** Subtitle */
    Subtitle: {
      /** Index */
      index: number
      /** Start */
      start: number
      /** End */
      end: number
      /** Content */
      content: string
      /** Speaker Id */
      speaker_id: string
      /** Segment Nr */
      segment_nr: number
    }
    /** SubtitlesDocument */
    SubtitlesDocument: {
      /** Subtitles */
      subtitles: components["schemas"]["Subtitle"][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_presigned_post_ingest_get_presigned_post_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["S3PostRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["S3PostResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_processing_ingest_process_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_media_urls_db_get_signed_urls_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["S3MediaUrlRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["S3MediaUrlResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  mongo_metadata_db_get_metadata_get: {
    parameters: {
      query: {
        /** @description The UUID of the media */
        media_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MetadataResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  search_solr_search_search_solr_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchQuery"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SearchResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_media_admin_list_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MediaListResponse"]
        }
      }
    }
  }
  check_processing_status_admin_status__media_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        media_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProcessingStatusResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_media_admin_delete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteMediaRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DeleteMediaResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  trigger_reindex_admin_reindex__media_id__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        media_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
