set positional-arguments
set shell := ["bash", "-cue"]
set fallback := true
set dotenv-load := true

comp_dir := justfile_directory()
output_dir := comp_dir / ".output"
build_dir := output_dir / "build"

# Default target if you do not specify a target.
default:
    just --list --unsorted

start *args:
    # TODO: Start odtp?
