set positional-arguments
set shell := ["bash", "-cue"]
set fallback := true
set dotenv-load := true

comp_dir := justfile_directory()
output_dir := comp_dir / ".output"
build_dir := output_dir / "build"

export CONTAINER_MGR := env("CONTAINER_MGR", "docker")

# Default target if you do not specify a target.
default:
    just --list --unsorted

start:
  just container::mgr compose -d up && \
  just container::mgr compose exec solr bash ~/load-data.sh

start-dev:
  just container::mgr compose -f docker-compose-dev.yml -d up && \
  just container::mgr compose exec \
    -f docker-compose-dev.yml \
    solr bash ~/load-data.sh
