set positional-arguments
set shell := ["bash", "-cue"]
set fallback := true
set dotenv-load := true

comp_dir := justfile_directory()
output_dir := comp_dir / ".output"
build_dir := output_dir / "build"

export CONTAINER_MGR := env("CONTAINER_MGR", "docker")

# Default target if you do not specify a target.
default:
    just --list --unsorted

image *args:
    just container::mgr build -f Containerfile . \
        -t "github.com/sdsc-ordes/debates-analytics/solr:latest"
