from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional, Dict
from enum import Enum

# Media

class S3MediaItem(BaseModel):
    name: str
    type: str
    description: str


class S3MediaPlayer(BaseModel):
    key: str
    type: str
    format: str


class Speaker(BaseModel):
    speaker_id: str
    name: str
    role_tag: str


class Subtitle(BaseModel):
    index: int
    start: float
    end: float
    content: str
    speaker_id: str
    segment_nr: int


class Segment(BaseModel):
    segment_nr: int
    speaker_id: str
    start: float
    end: float


class SpeakersDocument(BaseModel):
    speakers: List[Speaker]


class SegmentsDocument(BaseModel):
    segments: List[Segment]


class SubtitlesDocument(BaseModel):
    subtitles: List[Subtitle]


class EnumSubtitleType(str, Enum):
    transcript = "Transcript"
    translation = "Translation"


class S3Key(BaseModel):
    name: str
    type: str
    description: str


class Media(BaseModel):
    key: str
    type: str
    format: str


class DebateDocument(BaseModel):
    s3_prefix: str
    created_at: datetime
    s3_keys: List[S3Key]
    media: Media
    schedule: datetime
    public: bool
    type: str
    session: str


class S3MediaUrls(BaseModel):
    url: str = Field(..., description="Url")
    label: str = Field(..., description="Label for Url")


class MongoMetadataRequest(BaseModel):
    media_id: str = Field(..., description="media_id", examples=["df2afc83-7e69-4868-ba4c-b7c4afed6218"])


class MongoMetadataResponse(BaseModel):
    debate: Optional[DebateDocument] = None
    speakers: Optional[SpeakersDocument] = None
    segments: Optional[SegmentsDocument] = None
    subtitles: Optional[SubtitlesDocument] = None
    subtitles_en: Optional[SubtitlesDocument] = None


class S3MediaUrlRequest(BaseModel):
    media_id: str = Field(..., description="media_id", examples=["df2afc83-7e69-4868-ba4c-b7c4afed6218"])


class S3MediaUrlResponse(BaseModel):
    signedUrls: List[S3MediaUrls] = Field(..., description="List of presigned URLs")
    signedMediaUrl: str = Field(..., description="Presigned URL for the main media file")


# Solr Requests

class FacetFilter(BaseModel):
    facetField: str = Field(..., description="Solr facet field name", examples=["statement_type"])
    facetValue: str = Field(..., description="Solr facet field value", examples=["translation"])


class SolrRequest(BaseModel):
    queryTerm: str = Field(..., description="Solr query term can be empty", examples=["honor"])
    sortBy: str = Field(..., description="Solr sort option", examples=["start asc"])
    facetFields: List[str] = Field(
        ..., description="Solr facet field to return",
        examples = [["debate_schedule", "statement_type"]]
    )
    facetFilters: List[FacetFilter]  = Field(
        ..., description="Solr facet filters with set values"
    )

# Subtitle and Speaker Updates

class UpdateSpeakersRequest(BaseModel):
    media_id: str
    speakers: List[Speaker]


class UpdateSubtitlesRequest(BaseModel):
    media_id: str
    segmentNr: int
    subtitles: List[Subtitle]
    subtitleType: EnumSubtitleType

# Processing

class S3PostRequest(BaseModel):
    filename: str = Field(..., description="Original filename with extension (e.g., my_video.mp4)")


class S3PostResponse(BaseModel):
    postUrl: str = Field(..., description="The S3 endpoint URL to POST the file to")
    fields: Dict[str, str] = Field(..., description="Key-value fields required in the multipart form data")
    mediaId: str = Field(..., description="The unique media ID generated by the backend")
    s3Key: str = Field(..., description="The final S3 key where the file will be stored")


class ProcessRequest(BaseModel):
    s3_key: str = Field(..., description="The final S3 key where the file will be stored")
    media_id: str = Field(..., description="The unique job ID generated by the backend")
    title: str = Field(None, description="filename of the media")
