set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]
root_dir := `git rev-parse --show-toplevel`
comp_dir := justfile_directory()


default:
    just --list --unsorted

# Build the docs.
build *args:
    uv sync
    uv run mkdocs build

# Serve the docs.
serve *args:
    uv run mkdocs serve
